remote_theme: "mmistakes/minimal-mistakes"
name: "Víctor Martínez Gómez"
description: "I am a Computer Science Ph.D. student at University of Granada. I am focused on data mining, network analysis, machine learning, and artificial intelligence"
